# Install docker on a vagrant machine using ansible 
--- 
- hosts: 192.168.1.100 
  become: yes 
  tasks: 
    - name: Update the APT package index 
      apt: 
        update_cache: yes 
        allow_unauthenticated: yes
  
    - name: Ensure old version of Docker is not installed.
      apt:
        name: "{{ item  }}"
        state: absent 
      loop: 
        - docker 
        - docker-engine
        - docker.io
        - containerd 
        - runc
      when: not ansible_check_mode

    - name: Install required dependencies for Docker
      apt: 
        name: "{{ item }}"
        state: present 
      loop: 
        - apt-transport-https
        - ca-certificates
        - curl 
        - gnupg 
        - lsb-release 

    - name: Add Docker official GPG key 
      ansible.builtin.apt_key:
        url: "https://download.docker.com/linux/ubuntu/gpg"
        state: present 

    - name: Add Docker repository 
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64] "https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present 

    - name: Install Docker CE 
      apt: 
        name: docker-ce
        state: present 
        update_cache: yes 

    - name: Ensure docker is started 
      service: 
        name: docker 
        state: started 
        enabled: yes